<a href="https://colab.research.google.com/github/maneakansha36/my_first_repository/blob/main/Akankshanumpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

# Create array from 10 to 49 inclusive
arr = np.arange(10, 50)

# Reshape into 4x10 matrix
matrix = arr.reshape(4, 10)

# Extract the last column
last_column = matrix[:, -1]

print (arr)
print (matrix)
print (last_column)


[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]
[[10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]
 [30 31 32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47 48 49]]
[19 29 39 49]


In [ ]:
import numpy as np

# Create a 3x3 matrix filled with all 5s
matrix_5s = np.full((3, 3), 5)

# Create a 3x3 matrix with values from 1 to 9
matrix_nums = np.arange(1, 10).reshape(3, 3)

# Add the two matrices
addition_result = matrix_5s + matrix_nums

# Multiply them element-wise
multiplication_result = matrix_5s * matrix_nums

# Transpose of the multiplication result
transpose_result = multiplication_result.T

print("Matrix filled with 5s:\n", matrix_5s)
print("\nMatrix with values 1 to 9:\n", matrix_nums)
print("\nAddition Result:\n", addition_result)
print("\nElement-wise Multiplication Result:\n", multiplication_result)
print("\nTranspose of Multiplication Result:\n", transpose_result)


Matrix filled with 5s:
 [[5 5 5]
 [5 5 5]
 [5 5 5]]

Matrix with values 1 to 9:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]

Addition Result:
 [[ 6  7  8]
 [ 9 10 11]
 [12 13 14]]

Element-wise Multiplication Result:
 [[ 5 10 15]
 [20 25 30]
 [35 40 45]]

Transpose of Multiplication Result:
 [[ 5 20 35]
 [10 25 40]
 [15 30 45]]


In [ ]:
import numpy as np

# Create an array of 15 random integers between 10 and 100
arr = np.random.randint(10, 101, size=15)

# Replace values greater than 50 with -1
replaced_arr = np.where(arr > 50, -1, arr)

# Count how many values were replaced
count_replaced = np.sum(arr > 50)

print("Original Array:\n", arr)
print("\nArray after replacement:\n", replaced_arr)
print("\nNumber of values replaced:", count_replaced)


Original Array:
 [72 88 62 56 23 43 56 38 76 68 80 76 47 47 81]

Array after replacement:
 [-1 -1 -1 -1 23 43 -1 38 -1 -1 -1 -1 47 47 -1]

Number of values replaced: 10


In [ ]:
import numpy as np

# Step 1: Generate 5x4 random float array between 0 and 1
arr = np.random.rand(5, 4)

# Step 2: Find the row with maximum sum
row_sums = arr.sum(axis=1)
max_row_index = np.argmax(row_sums)
max_row = arr[max_row_index]

# Step 3: Normalize each row
row_min = arr.min(axis=1).reshape(-1, 1)
row_max = arr.max(axis=1).reshape(-1, 1)
normalized_arr = (arr - row_min) / (row_max - row_min)

print("Original Array:\n", arr)
print("\nRow sums:", row_sums)
print("Row with maximum sum (index {}):\n".format(max_row_index), max_row)
print("\nNormalized Array:\n", normalized_arr)


Original Array:
 [[0.98658896 0.06443034 0.22495145 0.21362413]
 [0.68879692 0.17466717 0.51576387 0.76102504]
 [0.82898832 0.34632024 0.47494133 0.4356597 ]
 [0.85688651 0.2499749  0.10247192 0.7232341 ]
 [0.24650303 0.70037527 0.60460648 0.75043667]]

Row sums: [1.48959487 2.14025299 2.08590959 1.93256745 2.30192145]
Row with maximum sum (index 4):
 [0.24650303 0.70037527 0.60460648 0.75043667]

Normalized Array:
 [[1.         0.         0.17407104 0.16178756]
 [0.87681905 0.         0.58172103 1.        ]
 [1.         0.         0.26647939 0.18509504]
 [1.         0.19551979 0.         0.82283957]
 [0.         0.90065873 0.71061627 1.        ]]


In [ ]:
import numpy as np

# Given array
arr = np.array([1, 3, 5, 3, 7, 9, 1, 5, 5])

# Find all unique elements
unique_elements = np.unique(arr)

# Find duplicates (elements appearing more than once)
unique_vals, counts = np.unique(arr, return_counts=True)
duplicates = unique_vals[counts > 1]

print("Original Array:", arr)
print("Unique Elements:", unique_elements)
print("Duplicates:", duplicates)


Original Array: [1 3 5 3 7 9 1 5 5]
Unique Elements: [1 3 5 7 9]
Duplicates: [1 3 5]


In [ ]:
import numpy as np

# Create 6x6 array with values from 1 to 36
arr = np.arange(1, 37).reshape(6, 6)

# Extract the middle 4x4 submatrix (rows 1:5 and cols 1:5)
submatrix = arr[1:5, 1:5]

# Extract even numbers from the submatrix
even_numbers = submatrix[submatrix % 2 == 0]

print("Original 6x6 Array:\n", arr)
print("\nMiddle 4x4 Submatrix:\n", submatrix)
print("\nEven Numbers from Submatrix:\n", even_numbers)


Original 6x6 Array:
 [[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]
 [19 20 21 22 23 24]
 [25 26 27 28 29 30]
 [31 32 33 34 35 36]]

Middle 4x4 Submatrix:
 [[ 8  9 10 11]
 [14 15 16 17]
 [20 21 22 23]
 [26 27 28 29]]

Even Numbers from Submatrix:
 [ 8 10 14 16 20 22 26 28]


In [ ]:
import numpy as np

# Generate array of shape (3, 4) with values from 0 to 11
arr = np.arange(12).reshape(3, 4)

# Reshape to (2, 6)
reshaped_2x6 = arr.reshape(2, 6)

# Flatten into 1D array
flattened = arr.flatten()

# Convert back to shape (4, 3)
reshaped_4x3 = flattened.reshape(4, 3)

print("Original (3x4) Array:\n", arr)
print("\nReshaped to (2x6):\n", reshaped_2x6)
print("\nFlattened 1D Array:\n", flattened)
print("\nReshaped back to (4x3):\n", reshaped_4x3)


Original (3x4) Array:
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

Reshaped to (2x6):
 [[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]]

Flattened 1D Array:
 [ 0  1  2  3  4  5  6  7  8  9 10 11]

Reshaped back to (4x3):
 [[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


In [ ]:
import numpy as np

# Original array
a = np.array([[1, 2], [3, 4]])

# Append a new row [5, 6]
a_with_row = np.vstack([a, [5, 6]])

# Append a new column [7, 8, 9]
# Reshape the column to match the number of rows
new_column = np.array([7, 8, 9]).reshape(-1, 1)
a_with_column = np.hstack([a_with_row, new_column])

print("Original Array:\n", a)
print("\nAfter appending new row:\n", a_with_row)
print("\nAfter appending new column:\n", a_with_column)


Original Array:
 [[1 2]
 [3 4]]

After appending new row:
 [[1 2]
 [3 4]
 [5 6]]

After appending new column:
 [[1 2 7]
 [3 4 8]
 [5 6 9]]


In [ ]:
import numpy as np

# Given arrays
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
c = np.array([7, 8, 9])

# Join them into a single array
joined_array = np.concatenate([a, b, c])

# Reshape into a 3x3 matrix
matrix_3x3 = joined_array.reshape(3, 3)

# Extract the diagonal elements
diagonal_elements = np.diag(matrix_3x3)

print("Joined Array:", joined_array)
print("\nReshaped 3x3 Matrix:\n", matrix_3x3)
print("\nDiagonal Elements:", diagonal_elements)


Joined Array: [1 2 3 4 5 6 7 8 9]

Reshaped 3x3 Matrix:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]

Diagonal Elements: [1 5 9]


In [ ]:
import numpy as np

# Create array of integers from 1 to 20
arr = np.arange(1, 21)

# Extract values divisible by 3 or 5
divisible_by_3_or_5 = arr[(arr % 3 == 0) | (arr % 5 == 0)]

# Count how many such values exist
count_divisible = divisible_by_3_or_5.size

print("Original Array:", arr)
print("Values divisible by 3 or 5:", divisible_by_3_or_5)
print("Count of values divisible by 3 or 5:", count_divisible)


Original Array: [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
Values divisible by 3 or 5: [ 3  5  6  9 10 12 15 18 20]
Count of values divisible by 3 or 5: 9


# Pandas

In [15]:
import seaborn as sns
data = sns.load_dataset('titanic')
sns.get_dataset_names()


['anagrams',
 'anscombe',
 'attention',
 'brain_networks',
 'car_crashes',
 'diamonds',
 'dots',
 'dowjones',
 'exercise',
 'flights',
 'fmri',
 'geyser',
 'glue',
 'healthexp',
 'iris',
 'mpg',
 'penguins',
 'planets',
 'seaice',
 'taxis',
 'tips',
 'titanic']

In [17]:
import pandas as pd
import seaborn as sns

# Load the Titanic dataset directly from seaborn
df = sns.load_dataset('titanic')

# Display the first 10 rows
display(df.head(10))

survived  pclass     sex   age  sibsp  parch     fare embarked   class  \
0         0       3    male  22.0      1      0   7.2500        S   Third   
1         1       1  female  38.0      1      0  71.2833        C   First   
2         1       3  female  26.0      0      0   7.9250        S   Third   
3         1       1  female  35.0      1      0  53.1000        S   First   
4         0       3    male  35.0      0      0   8.0500        S   Third   
5         0       3    male   NaN      0      0   8.4583        Q   Third   
6         0       1    male  54.0      0      0  51.8625        S   First   
7         0       3    male   2.0      3      1  21.0750        S   Third   
8         1       3  female  27.0      0      2  11.1333        S   Third   
9         1       2  female  14.0      1      0  30.0708        C  Second   

     who  adult_male deck  embark_town alive  alone  
0    man        True  NaN  Southampton    no  False  
1  woman       False    C    Cherbourg   yes  False  
2  woman       False  NaN  Southampton   yes   True  
3  woman       False    C  Southampton   yes  False  
4    man        True  NaN  Southampton    no   True  
5    man        True  NaN   Queenstown    no   True  
6    man        True    E  Southampton    no   True  
7  child       False  NaN  Southampton    no  False  
8  woman       False  NaN  Southampton   yes  False  
9  child       False  NaN    Cherbourg   yes  False

In [46]:
import pandas as pd
import seaborn as sns # Import seaborn as it was used to load the dataset initially

# Find the number of missing values in each column
missing_values = df.isnull().sum()

print("Number of missing values in each column:\n", missing_values)

Number of missing values in each column:
 survived         0
pclass           0
sex              0
age              0
sibsp            0
parch            0
fare             0
embarked         2
class            0
who              0
adult_male       0
deck           688
embark_town      2
alive            0
alone            0
age_group        0
dtype: int64


In [45]:
import pandas as pd


# Calculate survival percentage grouped by gender
survival_percentage = df.groupby('sex')['survived'].mean() * 100

print("Percentage of passengers who survived by gender:\n", survival_percentage)

Percentage of passengers who survived by gender:
 sex
female    74.203822
male      18.890815
Name: survived, dtype: float64


In [44]:
import pandas as pd



# Calculate statistics for the 'Age' column
average_age = df['age'].mean()
median_age = df['age'].median()
std_age = df['age'].std()

print(f"Average Age: {average_age:.2f}")
print(f"Median Age: {median_age:.2f}")
print(f"Standard Deviation of Age: {std_age:.2f}")

Average Age: 29.36
Median Age: 28.00
Standard Deviation of Age: 13.02


In [43]:
import pandas as pd



# Count the number of passengers in each class
passengers_per_class = df['pclass'].value_counts().sort_index()

print("Number of passengers in each class:\n", passengers_per_class)

Number of passengers in each class:
 pclass
1    216
2    184
3    491
Name: count, dtype: int64


In [42]:
import pandas as pd



# Filter passengers: female, under 18, and survived
filtered_passengers = df[(df['sex'] == 'female') & (df['age'] < 18) & (df['survived'] == 1)]

# Display the result
print(filtered_passengers)

     survived  pclass     sex    age  sibsp  parch      fare embarked   class  \
9           1       2  female  14.00      1      0   30.0708        C  Second   
10          1       3  female   4.00      1      1   16.7000        S   Third   
22          1       3  female  15.00      0      0    8.0292        Q   Third   
39          1       3  female  14.00      1      0   11.2417        C   Third   
43          1       2  female   3.00      1      2   41.5792        C  Second   
58          1       2  female   5.00      1      2   27.7500        S  Second   
68          1       3  female  17.00      4      2    7.9250        S   Third   
84          1       2  female  17.00      0      0   10.5000        S  Second   
156         1       3  female  16.00      0      0    7.7333        Q   Third   
172         1       3  female   1.00      1      1   11.1333        S   Third   
184         1       3  female   4.00      0      2   22.0250        S   Third   
208         1       3  femal

In [41]:
import pandas as pd


# Replace missing Age values with the median
df['age'].fillna(df['age'].median(), inplace=True)

# Verify that there are no missing values left
print(df['age'].isnull().sum())

# Optional: Display first 10 rows to see the changes
print(df.head(10))

0
   survived  pclass     sex   age  sibsp  parch     fare embarked   class  \
0         0       3    male  22.0      1      0   7.2500        S   Third   
1         1       1  female  38.0      1      0  71.2833        C   First   
2         1       3  female  26.0      0      0   7.9250        S   Third   
3         1       1  female  35.0      1      0  53.1000        S   First   
4         0       3    male  35.0      0      0   8.0500        S   Third   
5         0       3    male  28.0      0      0   8.4583        Q   Third   
6         0       1    male  54.0      0      0  51.8625        S   First   
7         0       3    male   2.0      3      1  21.0750        S   Third   
8         1       3  female  27.0      0      2  11.1333        S   Third   
9         1       2  female  14.0      1      0  30.0708        C  Second   

     who  adult_male deck  embark_town alive  alone age_group  
0    man        True  NaN  Southampton    no  False     Adult  
1  woman       False  

/tmp/ipython-input-1455819335.py:5: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['age'].fillna(df['age'].median(), inplace=True)


In [40]:
import pandas as pd
import numpy as np

# Using apply() with a custom function
def assign_age_group(age):
    if age < 18:
        return 'Child'
    elif age <= 60:
        return 'Adult'
    else:
        return 'Senior'

df['age_group'] = df['age'].apply(assign_age_group)

# Display first 10 rows
print(df[['age', 'age_group']].head(10))

# Optional: Count of passengers in each age group
print("\nCount of passengers in each age group:")
print(df['age_group'].value_counts())

    age age_group
0  22.0     Adult
1  38.0     Adult
2  26.0     Adult
3  35.0     Adult
4  35.0     Adult
5  28.0     Adult
6  54.0     Adult
7   2.0     Child
8  27.0     Adult
9  14.0     Child

Count of passengers in each age group:
age_group
Adult     756
Child     113
Senior     22
Name: count, dtype: int64


In [51]:
import pandas as pd



# Sort passengers by Fare in descending order and get top 5
top_fare_passengers = df.sort_values(by='fare', ascending=False).head(5)

# Display relevant columns
print(top_fare_passengers[['fare', 'pclass', 'sex', 'age',]])

         fare  pclass     sex   age
679  512.3292       1    male  36.0
258  512.3292       1  female  35.0
737  512.3292       1    male  35.0
88   263.0000       1  female  23.0
438  263.0000       1    male  64.0


In [53]:
import pandas as pd

# Load the Titanic dataset
# df = pd.read_csv('titanic.csv')  # replace with your file path if needed
# The titanic dataset is already loaded into the 'df' DataFrame

# Group by Pclass and Sex, then calculate average fare
average_fare = df.groupby(['pclass', 'sex'])['fare'].mean()

print("Average fare paid, grouped by Pclass and Sex:\n")
print(average_fare)

Average fare paid, grouped by Pclass and Sex:

pclass  sex   
1       female    106.125798
        male       67.226127
2       female     21.970121
        male       19.741782
3       female     16.118810
        male       12.661633
Name: fare, dtype: float64


In [56]:
import pandas as pd

# Load the Titanic dataset
# df = pd.read_csv('titanic.csv')  # replace with your file path
# The titanic dataset is already loaded into the 'df' DataFrame

# Rename columns: 'sex' → 'gender', 'fare' → 'ticket_fare'
df.rename(columns={'sex': 'gender', 'fare': 'ticket_fare'}, inplace=True)

# Verify the column names
print(df.columns)

Index(['survived', 'pclass', 'gender', 'age', 'sibsp', 'parch', 'ticket_fare',
       'embarked', 'class', 'who', 'adult_male', 'deck', 'embark_town',
       'alive', 'alone', 'age_group'],
      dtype='object')


In [58]:
import pandas as pd

# Load the Titanic dataset
# df = pd.read_csv('titanic.csv')  # replace with your file path

# Count passengers by Pclass and Survived
survival_count = df.groupby('pclass')['survived'].value_counts().unstack()

# Rename columns for clarity
survival_count.columns = ['Did_not_Survive', 'Survived']

print(survival_count)

        Did_not_Survive  Survived
pclass                           
1                    80       136
2                    97        87
3                   372       119


In [61]:
import pandas as pd

# Load the Titanic dataset
# df = pd.read_csv('titanic.csv')  # replace with your file path

# Group by Pclass and Sex, then calculate average age
average_age = df.groupby(['pclass', 'gender'])['age'].mean()

print("Average age of passengers grouped by class and gender:\n")
print(average_age)

Average age of passengers grouped by class and gender:

pclass  gender
1       female    33.978723
        male      38.995246
2       female    28.703947
        male      30.512315
3       female    23.572917
        male      26.911873
Name: age, dtype: float64
